### ISSUE TITLE
Can't use with create-react-app

### ISSUE THREAD

**Issue by vincerubinetti** [getify/CAF#13] opened 2020-01-16 19:53 UTC
Hello, I tagged you on Twitter about this a few days ago, but I figured it was okay to open an issue here. I feel like `create-react-app` is used by enough people (80k stars on GitHub) that it's worth looking into this issue.

### How to reproduce the error

Make a new `create-react-app` app:

```
npx create-react-app my-test-app
cd my-test-app
```

Install caf:

```
npm install caf
```

Include `caf` in any `/src` file -- say `App.js` -- as specified in the readme:

`var CAF = require("caf");`

Save the changes and run the app:

`npm start`

Observe the following error, when running locally:

`Error: Cannot find module '/dist/abortcontroller-polyfill-only.js'`

Or observe the following error when running on CodeSandbox:

```
ModuleNotFoundError
Could not find module in path: 'caf/dist/abortcontroller-polyfill-only.js' relative to '/node_modules/caf/index.js'
```

### CodeSandbox for convenient testing

https://codesandbox.io/s/frosty-tree-cwe5z

---

I'll post comments here as I try to figure out how to fix the issue.

**Comment by getify** [comment] 2020-01-16 20:12
Did you specifically run a `npm install caf` command somewhere in the process, or does CRA auto-magically install it for you?

Have you looked to see if the `dist/abortcontroller-polyfill-only.js` file exists? This file is created by the "build process" for CAF, which is normally executed for you on a `npm install caf` installation.

If you have CAF but this `dist/` file is missing, it means the build process wasn't executed (for some reason?). That should be fixed then by issuing `npm run build` from inside the CAF directory.

If you *do* have both the `dist/` files, then something else is weird, perhaps some assumptions CRA is making about relative paths?

**Comment by vincerubinetti** [comment] 2020-01-16 20:16
Yes, sorry, I forgot to put it in the reproduce steps, but yes I did run `npm install caf`.

Yes, `dist/abortcontroller-polyfill-only.js` exists under `node_modules/caf`.

It's probably something weird going on with CRA's webpack configuration, but I'm having a hard time making sense of anything.

**Comment by vincerubinetti** [comment] 2020-01-16 20:20
Perhaps it'd be valuable to show you the contents of the `/dist` folder files, to make sure they're being built appropriately? Maybe CRA is doing something that makes your build process behave differently (environment variable or something)?

abortcontroller-polyfill-only.js https://pastebin.com/8ujMgi3u
caf.js https://pastebin.com/i3RPxZvY

**Comment by getify** [comment] 2020-01-16 20:20
If the files are in the `dist/` folder, then CAF has at least done its job. I'm lost beyond that.

I've never used CRA nor webpack, so I'm afraid I'm not much help in troubleshooting its internal behaviors/defaults. :/

**Comment by getify** [comment] 2020-01-16 20:22
> Perhaps it'd be valuable to show you the contents of the /dist folder files

Those are minified files so I'm not 100% sure, but it sure seems at a glance like the files are correct as expected. Both those files *look* to me like how CAF's build tool creates them, not as having been modified from CRA/webpack.

**Comment by getify** [comment] 2020-01-16 20:24
BTW, your app only really needs the polyfill if you're supporting older browsers that don't have `AbortController`. Not sure how or why CRA/webpack are making the determination that the polyfill is necessary?

**Comment by vincerubinetti** [comment] 2020-01-16 20:27
Ah, I definitely don't need the polyfill, as I'm not supporting IE. But I thought it was always included by your build process?

It seems like you're saying it takes a flag or makes some determination to decide whether to include it or not? Maybe this is the source of the issue. Any overview you could give me about how this works would be helpful.

**Comment by vincerubinetti** [comment] 2020-01-16 20:28
Btw, my potential solution to this is to port your code over to just use ES6 module imports and exports, and then use Babel to compile it (backward to AMD? not sure how it works), which is how I've made packages (in my very limited experience).

Have you looked into doing this, or would it not be possible to get the backwards compatibility you would want for such a widely used library.

**Comment by vincerubinetti** [comment] 2020-01-16 20:46
Ahhh!! I think it is related to #12. 

Changing `browser` in `node_modules/caf/package.json` to `./dist/caf.js` makes it work just fine. 

Also if in that CodeSandbox you roll back the `caf` version number to pre-`8.0.0`, it starts working:

![image](https://user-images.githubusercontent.com/8326331/72561475-4ea63300-3877-11ea-9427-0d27f74dfab4.png)




Perhaps that pull request should be merged soon!

**Comment by getify** [comment] 2020-01-16 21:14
I'm happy to merge #12, but to be honest, the reason why I haven't until now is, not knowing or understanding CRA/webpack, the problem and the error message being given never made any sense to me. I didn't want to just merge that fix without someone being able to explain why `src/caf.js` was wrong or broken.

----

As an aside, this is kind of my problem with modern JS tooling, that it does all this magical stuff that nobody seems to understand, and only works if you just happen to luck out and be on the happy path. I don't like having to guess and accidentally get something working. It should be clear and obvious what a package maintainer is supposed to do to make their code work.

With respect to your desires to port the code to ES modules... feel free if you'd like to. But again, CAF has worked fine in its UMD format (in both browser and node) for several years. So it's not CAF's fault that CRA/webpack don't work well, it's CRA/webpack at fault for making too many magical assumptions.

----

Just for posterity, let's try to sort out the error message you posted at the top of the thread...

> Could not find module in path: 'caf/dist/abortcontroller-polyfill-only.js' relative to '/node_modules/caf/index.js'

The first part of that error message was confusing to me, because that file **should** be present if the CAF build process has indeed run. That's what my replies on twitter and earlier in this thread were focused on. But you said it **is** present... so that can't be the problem.

And moreover, why is CRA/webpack even focused on this file? Nothing about `caf.js` references the polyfill. I couldn't figure out why CRA/webpack were even trying to mess with the polyfill.

But then I just noticed the second part of the error, about referencing `index.js`. Hmmmm... why is CRA/webpack looking at `index.js`? **THAT** file is only supposed to be used when loading CAF in a node environment, not for bundling stuff for the web.

Indeed, if [you look at `index.js`](https://github.com/getify/CAF/blob/master/index.js), it **does** load the polyfill. That's because Node definitely doesn't have `AbortController`, so it absolutely needs the polyfill for CAF to work.

```js
"use strict";

var path = require("path");

require(path.join(__dirname,"dist","abortcontroller-polyfill-only.js"));
module.exports = require(path.join(__dirname,"src","caf.src.js"));
```

But `index.js` loads the polyfill from a path relative to where `index.js` is located (uses `__dirname`). So, as far as I'm aware, that should always be the root of CAF, which means the `./dist/abortcontroller-polyfill-only.js` path should always be valid, no matter what CRA/webpack do.

**Note:** `index.js` here includes `src/caf.js` instead of `dist/caf.js` because I assumed that if someone wanted to debug CAF while using it in Node (looking at stack traces, etc), they'd prefer to look at the fully formatted source code of CAF rather than the minified code (which is designed for the browser).

So... a bunch of questions remain... and until I get answers to these, I'm skeptical of just merging #12 and moving on.

1. Why is CRA/webpack looking at `./index.js` when the `package.json` key tells it to look at `src/caf.js` (or `dist/caf.js`)?

2. How is CRA/webpack using `index.js` in such a way that the `__dirname` pathing to find the polyfill in `dist/` doesn't work?

3. Why does changing from `src/caf.js` to `dist/caf.js` magically make CRA/webpack not have any trouble with the code?

4. Is CRA/webpack trying to unconditionally bundle the polyfill? Why? What logic does CRA/webpack use to determine that the polyfill is needed? I would think CRA/webpack would like to copy the polyfill over into whatever it's building for deployment, but only include it in bundles that are targeted to older browsers. But I have no idea how that logic works in CRA/webpack?

5. Is there some other way to tell CRA/webpack to ignore the polyfill? That way, users can manually decide if they want to copy over the polyfill or not, instead of letting CRA/webpack make that decision.

**Comment by vincerubinetti** [comment] 2020-01-16 21:34
I'll have to take some time to digest what you said. And I think this all might be above my pay-grade to comment on productively. But I want to say some things, for now, just in case they're helpful.

1. It might be that CRA and/or webpack don't like the entry point of a package being in the `/src` directory. As a layman, I would expect the entry point to always be somewhere in the `/dist` or `/build` folder, as that's where the compiled/bundled/finalized package gets put.
2. Here is a very quick test of what this library could look like using ES6 imports and a simpler build configuration: https://github.com/vincerubinetti/CAF
3. Trying to figure out what was going on in this library's configuration was very difficult for me to understand, and I have to believe there's an easier way to set it all up. And perhaps some of the things you've tried to include, like your **Note:** above, add complexity that isn't worth the value it adds. Even if you want to keep it, there might be a less confusing way to set it all up.
4. Even if you don't want to do 4, using the newer import/export syntax over the UMD/require/etc stuff where possible might be easier to read and debug for simpletons like me. Assuming you can still compile everything with enough backwards compatibility.
5. I agree that JS tooling, and hell everything about the web ecosystem, is an adhoc convoluted mess. I can sympathize with your frustration.

**Comment by getify** [comment] 2020-01-16 21:53
> Trying to figure out what was going on in this library's configuration was very difficult for me to understand

I'm sorry that's the case, but I think that's partly because you're used to the tooling doing everything magically for you. My approach to delivery and building of this tool is about as uncomplicated and unsophisticated (unmagical) as it gets. I'm very old school.

The build tool just takes the file from the `src/` directory, runs it through a minifier, and drops that into `dist/`. It also takes the polyfill from inside node_modules, minifies it, and sticks it in `dist/`. That's it. It's really no more complicated than that.

> using the newer import/export syntax over the UMD/require/etc stuff where possible might be easier to read and debug for simpletons like me

Ideally, you shouldn't need to read CAF's source code at all. I certainly don't build packages like this with the main use case being that I want people to have to read my code. In fact, I try to make it FAR easier for them to use. It should "just work" out of the box.

The README for this project lists out some pretty dead-simple steps to take. `npm install` then a single line to include `CAF` in your node file (using `require(..)`). That is literally all you should have to do.

The fact that tooling like CRA or webpack can't work with that is, in my opinion, their fault, for trying to make too many assumptions. I know of lots of people that have just `npm install`d CAF and started using it right away without any problems.

I don't deny that CRA/webpack seem to be incompatible and that those like you who use it are having a problem. I just think the problem is the tooling.

In fact, it's precisely my desire to keep things as simple and uncomplicated as possible that has me NOT using the ES modules format. If I were to make the source code be ES modules, then this project would have to ship with a more sophisticated build process for creating a backwards-compatible transpiled bundle for use in browsers that don't support ES modules, or for use in Node versions earlier than the (very) recent ES modules support.

By contrast, since I write my code in UMD format, it "just works" as-is in all browsers, and in all versions of Node. No fancy transpilation necessary. Even the minifier isn't necessary, but I include it for good measure, since it saves a couple of KB.

So I think what you're experiencing is a recency bias, that since your context and typical environment is more geared toward the "modern" and the magic of tooling like CRA and webpack, when you encounter a simple old-school uncomplicated project like mine, it feels foreign and weird.

Ideally, you wouldn't have had to go through any of the steps or frustration that you faced, because ideally tooling should have been smart enough to work not only with "modern" code but also classic old-school code. That's sadly not the case, apparently.

But even then, I don't think the problem was ever in CAF's code, so the frustrations you faced in trying to understand my code were regrettable but not necessary. The source of the problem has always seemed to be with webpack's configurations, which at most should have led to looking at CAF's `package.json`.

I'm sorry for your frustrations. I hope someone who understands CRA/webpack will swoop in and grace us with the magical wisdom of how their tools work, so those questions above are adequately answered, and whatever proper fixes to configuration are applied.

I doubt this will result in any code changes to CAF at all. I think it's going to be in `package.json` at best.

**Comment by DrewML** [comment] 2020-01-17 17:05
> Does webpack prefer to have access to the source file for its bundling/transpilation/whatever? Or it is actually better to point it at an already "built" (minified) file?

Good question! In an ideal world exposing webpack to the source file is better. But, webpack can also ingest source-maps, so whether you expose src or dist + sourcemaps, folks should be good. Most people want unbundled for the sake of things like tree shaking, but won't really matter for a dep-free lib like this

**Comment by DrewML** [comment] 2020-01-17 17:06
> I really wish webpack or CRA were issuing a warning or error if they encounter an issue where the path listed in a package.json key is missing, instead of just silently skipping over it. :(

Same. Ideally webpack would not use its normal module lookup fallback behavior for those fields in the way it does with other module resolution.

**Comment by getify** [comment] 2020-01-17 17:12
So it's more canonical/correct/expected to point it at `src/caf.src.js`, it seems. Agreed that this is the best fix here?

**Comment by DrewML** [comment] 2020-01-17 17:16
> So it's more canonical/correct/expected to point it at src/caf.src.js, it seems. Agreed that this is the best fix here?

Yep! Agreed.

**Closed** 2020-01-17 20:30 UTC

**Comment by getify** [comment] 2020-01-17 20:58
Just released v9.0.0. Hopefully this is resolved now! Please let me know.

**Comment by MartinMalinda** [comment] 2020-05-15 21:09
I just experienced this when doing production build with `vuepress`. Changing the `main` value to `./src/caf.src.js` just like it's in the `browser` solves the issue.

**Comment by getify** [comment] 2020-05-16 02:08
Does 9.x work for you?

**Comment by MartinMalinda** [comment] 2020-05-16 08:15
I only tried 9.X and the issue is there.

With vuepress, it's all fine when I do development build, most likely because it's just a browser SPA.
It only breaks when I do a production build, because there's HTML prerendering via node. I don't need to do any fetching on the server side though, CAF is only used on client side in my docs application.

This is the repo:
https://github.com/MartinMalinda/vue-concurrency

**Comment by getify** [comment] 2020-05-16 17:59
Sorry, I guess I was confused. It seems you have a separate problem. This issue was about needing to change what the `browser` field points to, which I was happy to accommodate since it seemed to fix CRA.

But you're saying that vue needs the `main` to change as well, and that's different. You could file a separate issue for that so we could explore what's wrong with vue's tooling, but `main` is not going to be changed to point at the src file... it's intentionally set to point at the `index.js` because it's including the polyfill for the benefit node users. Seems like vue's tooling needs to be fixed (or differently configured).

**Comment by MartinMalinda** [comment] 2020-05-16 18:06
@getify I could have been more specific, sorry about that.

I'll investigate more.

I'm developping a vue plugin that uses CAF. The issue already appears when I try to create a production build with `vuepress` - which I use for the addon documentation.

I'll also test if the error is present in a vue app that consumes the vue plugin.

I'll create an issue afterwards.

**Comment by MartinMalinda** [comment] 2020-05-20 10:41
I can't reproduce the issue anymore 🎉 . I think I might have experienced before because I had `caf` in `devDependecies` and `peerDependencies`. Moving it to `dependencies` where it probably should seems to have solved the problem. No need to create new issue I think.
